name: Build & Deploy

on: [push, workflow_dispatch]

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Prerequisites
        run: sudo apt install nodejs -y
      
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Install Package
        run: npm install
        
      - name: Build Astro
        run: npm run build
        
      - name: Save build output as artifact
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: ./dist

  Deploy:
    runs-on: ubuntu-latest
    needs: Build
    steps:
      - name: Download build output artifact
        uses: actions/download-artifact@v3
        with:
          name: build-output
          path: ./dist
          
      - name: Compress build output
        run: tar -czf pages-artifact.tar.gz -C ./dist .
 
      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: pages-artifact.tar.gz