name: Build

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Prerequisites
        run: sudo apt install nodejs -y
      
      - name: Checkout Repository
        uses: actions/checkout@v4
        
      - name: Install Package
        run: npm install
        
      - name: Build Astro
        run: npm run build